spring:
  application:
    name: opinions-service
  threads:
    virtual:
      enabled: true
server:
  port: 7777


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
