spring:
  application:
    name: opinions-service
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      auto-index-creation: true
server:
  port: 7777



eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true



kafka:
  consumer:
    consumer-number: 1
    securityProtocol: SASL_SSL
    saslMechanism: SCRAM-SHA-512
    max-poll-records: 10000
    request-timeout-ms: 11000
    connections-max-idle-ms: 240000
    poll-timeout-ms: 1000
    auto-offset-reset: earliest
    ssl:
      enabled: false
    retry:
      max-retries: 5
      back-off-period: 500
      backoff-period-service-unavailable: 5000
    retry-backoff-ms: 1000
    max-poll-interval-ms: 30000
  producer:
    securityProtocol: SASL_SSL
    saslMechanism: SCRAM-SHA-512
    retry-backoff-in-ms: 100
    retries: 5
    ssl:
      #    keyStore: ${server.ssl.keystore}
      #    keyStoreType: ${server.ssl.keystoretype}
      #    keyStorePassword: ${server.ssl.keystorepassword}
      #    keyPassword: ${server.ssl.keypassword}
      #    trustStore: ${server.ssl.truststore}
      #    trustStorePassword: ${server.ssl.truststorepassword}
      #    trustStoreType: ${server.ssl.truststoretype}
      enabled: false
