apiVersion: v1
kind: ConfigMap
metadata:
  name: opinions-config
data:
  KAFKA_BOOTSTRAP_SERVERS: "192.168.0.235:29092"
  MONGO_URI: "mongodb://192.168.0.235:27018/opinions"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opinions-config-properties
data:
  config.yml: |
    eureka:
      client:
        enabled: false

    spring:
      data:
        mongodb:
          uri: ${MONGO_URI}

    kafka:
      producer:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
        security-protocol: PLAINTEXT
      consumer:
        application-id: opinion-service
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
        security-protocol: PLAINTEXT
        user-details-data-topic: outsource-me-api-user-data

    opinions:
      topics:
        user-opinions-data: outsource-me-api-user-opinions-details
    fixtures:
      enabled: true
