spring:
  datasource:
    url: jdbc:mysql://localhost:3308/user_profile
    username: root
    password: 12345

eureka:
  client:
    enabled: false


services:
  auth:
    url: http://localhost:9002
    userRegisteredTopic: outsource-me-api-user-registered
  notifications:
    login: 1234
    externalTopic: outsource-me-api-notifications


feign:
  connection:
    type: URI


kafka:
  producer:
    bootstrap-servers: localhost:29092
    security-protocol: PLAINTEXT
  consumer:
    application-id: user-profile-service
    bootstrap-servers: localhost:29092
    security-protocol: PLAINTEXT
    #    sasl-jaas-config: org.apache.kafka.common.security.scram.ScramLoginModule required username="dev" password="dev123"

user-profile:
  topics:
    USER_DATA: outsource-me-api-user-data
  storage:
    rootLocation: user-profile/storage
    thumbnailDir: thumbnails