version: '3.9'
services:
  mysql:
    container_name: 'outsource-me-mysql'
    image: 'mysql:latest'
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
    networks:
      - outsource_me
  mongo:
    container_name: 'outsource-me-mongo'
    image: 'mongo:latest'
    ports:
      - '27018:27017'
    volumes:
      - './data/mongo:/data/db'
    networks:
      - outsource_me

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    #    volumes:
    #      - ./kafka/zookeeper/data:/var/lib/zookeeper/data
    #      - ./kafka/zookeeper/log:/var/lib/zookeeper/log
    ports:
      - 22181:2181
    networks:
      - outsource_me

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #    volumes:
      #      - ./kafka/broker/data:/var/lib/kafka/data
    networks:
      - outsource_me
  mailhog:
    image: mailhog/mailhog
    container_name: outsource-me-mailhog
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - outsource_me

  elasticsearch:
    container_name: outsource_me_api-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      ELASTIC_PASSWORD: elastic
      xpack.security.transport.ssl.enabled: false
      xpack.security.http.ssl.enabled: false

    ports:
      - "9200:9200"
    networks:
      - outsource_me

  redis:
    image: redis:7.2.4-alpine
    container_name: outsource-me-redis
    ports:
      - '6379:6379'
    networks:
      - outsource_me
networks:
  outsource_me:











