apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  labels:
    app: notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: shreddler/outsource_me-notifications:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: notifications-config
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          livenessProbe:
            httpGet:
              port: 9001
              path: /manage/health
            initialDelaySeconds: 20
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              port: 9001
              path: /manage/health
            initialDelaySeconds: 5
            timeoutSeconds: 10

      volumes:
        - name: config-volume
          configMap:
            name: notifications-config-properties
        - name: env-volume
          configMap:
            name: notifications-config

---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  ports:
    - targetPort: 9001
      port: 80
      protocol: TCP
  selector:
    app: notifications-service
