spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/auth

server:
  tomcat:
    accesslog:
      enabled: false

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secretKey: '614E645267556B58703273357638792F413F4428472B4B6250655368566D597133743677397A244326452948404D635166546A576E5A7234753778214125442A'



auth:
  settings:
    sign-in:
      account-activation: VERIFY_EMAIL
      register-event-topic: outsource-me-api-user-registered
    roles:
      - ROLE_DEVELOPER
      - ROLE_PRINCIPLE
      - ROLE_ADMIN
      - ROLE_EDITOR

    event-broker: internal




kafka:
  bootstrap-servers: localhost:29092
  security-protocol: PLAINTEXT
