spring:
  application:
    name: static-data-service
  threads:
    virtual:
      enabled: true
server:
  port: 8888



eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
static-data:
  technology-csv-file: classpath:technologies.csv
