spring:
  application:
    name: gateway
  threads:
    virtual:
      enabled: true

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            maxAge: 180
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      httpclient:
        response-timeout: 5000
        connect-timeout: 1000
      routes:
        - id: user-profile
          uri: lb://user-profile-service
          predicates:
            - Path=/users/**, /auth/register, /auth/resend_password_reset_link
            - NoPath=/api/v1/users/register,/api/v1/users/resend_password_reset_link
          filters:
            - RewritePath=/users(?<segment>.*),/api/v1/users$\{segment}
            - RewritePath=/auth/register, /api/v1/users/register
            - RewritePath=/auth/resend_password_reset_link, /api/v1/users/resend_password_reset_link
        - id: job-offer
          uri: lb://job-offer-service
          predicates:
            - Path=/job-offers/**, /applications/**
          filters:
            - RewritePath=/job-offers(?<segment>.*),/api/v1/job-offers$\{segment}
            - RewritePath=/applications(?<segment>.*),/api/v1/applications$\{segment}
        - id: opinions
          uri: lb://opinions-service
          predicates:
            - Path=/opinions/**
          filters:
            - RewritePath=/opinions(?<segment>.*),/api/v1/opinions$\{segment}
        - id: static-data
          uri: lb://static-data-service
          predicates:
            - Path=/static-data/**
          filters:
            - RewritePath=/static-data/(?<segment>.*),/api/v1/static-data/$\{segment}
        - id: notifications
          uri: lb://notifications-service
          predicates:
            - Path=/notifications, /notifications/*/mark_seen
          filters:
            - RewritePath=/notifications/(?<segment>.*)/mark_seen, /api/v1/notifications/(?<segment>.*)/mark_seen
            - RewritePath=/notifications(?<segment>.*), /api/v1/notifications?channel=INTERNAL&(?<segment>.*)
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/access_token,/auth/refresh_token
          filters:
            - RewritePath=/auth/(?<segment>.*),/v1/auth/$\{segment}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin





eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5


management:
  health:
    defaults:
      enabled: false
  endpoint:
    metrics:
      enabled: false
    health:
      show-details: always
  endpoints:
    web:
      base-path: /manage
      exposure:
        exclude: health,info,gateway



