spring:
  datasource:
    url: jdbc:mysql://localhost:3308/job_offer
    username: root
    password: 12345
  elasticsearch:
    uris: http://localhost:9200
    password: elastic
    username: elastic
  liquibase:
    url: jdbc:mysql://localhost:3308/job_offer
    user: root
    password: 12345
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    enabled: false


services:
  notifications:
    login: 1234
    externalTopic: outsource-me-api-notifications
  opinions:
    userOpinionsDetailsTopic: outsource-me-api-user-opinions-details
  static-data:
    url: http://localhost:8888



feign:
  connection:
    type: URI


kafka:
  producer:
    bootstrap-servers: 192.168.0.235:29092
    security-protocol: PLAINTEXT
  consumer:
    application-id: job-offer-service
    bootstrap-servers: 192.168.0.235:29092
    security-protocol: PLAINTEXT
    user-details-data-topic: outsource-me-api-user-data
    #    sasl-jaas-config: org.apache.kafka.common.security.scram.ScramLoginModule required username="dev" password="dev123"

job-offers:
  service-id: job-offers-service
  user-thumbnail-server-url: http://localhost:8080/users/thumbnails
  check-job-offer-expiration-cron: 0 0 1 * * *
  recalculate-job-offers-popularity-rate-cron: 0 0 1 * * *
  elasticsearch:
    boostrap-type: reindex
  topics:
    JOB_OFFER_DATA: outsource-me-api-job-offer-data
  notifications:
    job-offer-application-email:
      subject: "Masz nową aplikacje na oferte %s"
      body: "Użytkownik %s właśnie zaaplikował na twoją oferte <b>%s</b>. Sprawdź to!"
    job-offer-application-internal-message:
      body: "Użytkownik %s właśnie zaaplikował na twoją oferte"
    job-offer-expired-internal-message-to-principal:
      body: "Oferta %s właśnie wygasła"
    job-offer-expired-email-to-principal:
      subject: "Twoja oferta %s właśnie wygasła"
      body: "Twoja oferta %s właśnie wygasła. Dziękujemy za korzystanie z naszej platformy"
    job-offer-expired-internal-message-to-appliers:
      body: "Oferta %s na którą zaaplikowałeś właśnie wygasła"
    job-offer-expired-email-to-appliers:
      subject: "Oferta %s na którą zaaplikowałeś właśnie wygasła"
      body: "Oferta %s na którą zaaplikowałeś właśnie wygasła. Oczekuj na mailwy kontakt od zleceniodawcy. Dziękujemy za korzystanie z naszej platformy i życzymy powodzenia w dalszym poszukiwaniu zleceń"
  cache:
    for-you-cache-ttl: 3h
    global-cache-ttl: 12h
    job-offers-cache-ttl: 1h


storage:
  root-location: job-offer/storage
  attachments-location: attachments

fixtures:
  enabled: true
