apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  config.yml: |
    spring:
      cloud:
        kubernetes:
          enabled: true
    eureka:
      client:
        enabled: false
