apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      serviceAccountName: monitoring-service-account
      containers:
        - name: gateway-service
          image: shreddler/outsource_me-gateway:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          livenessProbe:
            httpGet:
              port: 8080
              path: /manage/health
            initialDelaySeconds: 20
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              port: 8080
              path: /manage/health
            initialDelaySeconds: 5
            timeoutSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  ports:
    - targetPort: 8080
      port: 80
      protocol: TCP
  selector:
    app: gateway-service
