eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL}


spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

kafka:
  producer:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    security-protocol: PLAINTEXT
  consumer:
    application-id: opinion-service
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    security-protocol: PLAINTEXT
    user-details-data-topic: outsource-me-api-user-data

opinions:
  topics:
    user-opinions-data: outsource-me-api-user-opinions-details
