eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/static-data

static-data:
  postal-code-data-url: https://www.kody-pocztowe.dokladnie.com/kody.csv.zip
  open-street-map-url: https://nominatim.openstreetmap.org/search?format=json
  cache:
    stat-cache-ttl: 6h
  about-us-image-server-url: http://localhost:8888/api/v1/static-data/about-us/image

fixtures:
  enabled: true


storage:
  root-location: static-data/storage
  about-us-image-dir: about-us
