eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_URL}


spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

static-data:
  postal-code-data-url: https://www.kody-pocztowe.dokladnie.com/kody.csv.zip
  open-street-map-url: https://nominatim.openstreetmap.org/search?format=json
  cache:
    stat-cache-ttl: 6h
  about-us-image-server-url: http://localhost:8888/api/v1/static-data/about-us/image


storage:
  root-location: storage
  about-us-image-dir: about-us
